# Generated by Django 5.2 on 2026-04-09 11:01

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Community = apps.get_model('main', 'Community')
    for community in Community.objects.all():
        if not community.slug:
            base_slug = slugify(community.name)
            slug = base_slug
            counter = 1
            while Community.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            community.slug = slug
            community.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
